server:
 application:
    name: greeting-service
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
greeting-service:
  greeting: "Pronto"
  default-value: "Mondo docker prod"